export const ADD_ANNOUNCEMENT_REQUEST = 'ADD_ANNOUNCEMENT_REQUEST';
export const ADD_ANNOUNCEMENT_SUCCESS = 'ADD_ANNOUNCEMENT_SUCCESS';
export const ADD_ANNOUNCEMENT_FAILURE = 'ADD_ANNOUNCEMENT_FAILURE';

export const GET_ANNOUNCEMENT_LIST_REQUEST = 'GET_ANNOUNCEMENT_LIST_REQUEST';
export const GET_ANNOUNCEMENT_LIST_SUCCESS = 'GET_ANNOUNCEMENT_LIST_SUCCESS';
export const GET_ANNOUNCEMENT_LIST_FAILURE = 'GET_ANNOUNCEMENT_LIST_FAILURE';

export const GET_ANNOUNCEMENT_DETAIL_REQUEST = 'GET_ANNOUNCEMENT_DETAIL_REQUEST';
export const GET_ANNOUNCEMENT_DETAIL_SUCCESS = 'GET_ANNOUNCEMENT_DETAIL_SUCCESS';
export const GET_ANNOUNCEMENT_DETAIL_FAILURE = 'GET_ANNOUNCEMENT_DETAIL_FAILURE';

export const DELETE_ANNOUNCEMENT_REQUEST = 'DELETE_ANNOUNCEMENT_REQUEST';
export const DELETE_ANNOUNCEMENT_SUCCESS = 'DELETE_ANNOUNCEMENT_SUCCESS';
export const DELETE_ANNOUNCEMENT_FAILURE = 'DELETE_ANNOUNCEMENT_FAILURE';