export const ADD_APPLICANT_REQUEST = 'ADD_APPLICANT_REQUEST';
export const ADD_APPLICANT_SUCCESS = 'ADD_APPLICANT_SUCCESS';
export const ADD_APPLICANT_FAILURE = 'ADD_APPLICANT_FAILURE';

export const GET_APPLICANT_LIST_REQUEST = 'GET_APPLICANT_LIST_REQUEST';
export const GET_APPLICANT_LIST_SUCCESS = 'GET_APPLICANT_LIST_SUCCESS';
export const GET_APPLICANT_LIST_FAILURE = 'GET_APPLICANT_LIST_FAILURE';

export const UPDATE_APPLICANT_STATUS_REQUEST = 'UPDATE_APPLICANT_STATUS_REQUEST';
export const UPDATE_APPLICANT_STATUS_SUCCESS = 'UPDATE_APPLICANT_STATUS_SUCCESS';
export const UPDATE_APPLICANT_STATUS_FAILURE = 'UPDATE_APPLICANT_STATUS_FAILURE';

export const GET_APPLICANT_DETAIL_REQUEST = 'GET_APPLICANT_DETAIL_REQUEST';
export const GET_APPLICANT_DETAIL_SUCCESS = 'GET_APPLICANT_DETAIL_SUCCESS';
export const GET_APPLICANT_DETAIL_FAILURE = 'GET_APPLICANT_DETAIL_FAILURE';

export const DELETE_APPLICANT_REQUEST = 'DELETE_APPLICANT_REQUEST';
export const DELETE_APPLICANT_SUCCESS = 'DELETE_APPLICANT_SUCCESS';
export const DELETE_APPLICANT_FAILURE = 'DELETE_APPLICANT_FAILURE';