export const ADD_ATTENDANCE_REQUEST = 'ADD_ATTENDANCE_REQUEST';
export const ADD_ATTENDANCE_SUCCESS = 'ADD_ATTENDANCE_SUCCESS';
export const ADD_ATTENDANCE_FAILURE = 'ADD_ATTENDANCE_FAILURE';

export const GET_ATTENDANCE_LIST_REQUEST = 'GET_ATTENDANCE_LIST_REQUEST';
export const GET_ATTENDANCE_LIST_SUCCESS = 'GET_ATTENDANCE_LIST_SUCCESS';
export const GET_ATTENDANCE_LIST_FAILURE = 'GET_ATTENDANCE_LIST_FAILURE';

export const UPDATE_ATTENDANCE_STATUS_REQUEST = 'UPDATE_ATTENDANCE_STATUS_REQUEST';
export const UPDATE_ATTENDANCE_STATUS_SUCCESS = 'UPDATE_ATTENDANCE_STATUS_SUCCESS';
export const UPDATE_ATTENDANCE_STATUS_FAILURE = 'UPDATE_ATTENDANCE_STATUS_FAILURE';

export const GET_ATTENDANCE_DETAIL_REQUEST = 'GET_ATTENDANCE_DETAIL_REQUEST';
export const GET_ATTENDANCE_DETAIL_SUCCESS = 'GET_ATTENDANCE_DETAIL_SUCCESS';
export const GET_ATTENDANCE_DETAIL_FAILURE = 'GET_ATTENDANCE_DETAIL_FAILURE';

export const DELETE_ATTENDANCE_REQUEST = 'DELETE_ATTENDANCE_REQUEST';
export const DELETE_ATTENDANCE_SUCCESS = 'DELETE_ATTENDANCE_SUCCESS';
export const DELETE_ATTENDANCE_FAILURE = 'DELETE_ATTENDANCE_FAILURE';


export const GET_ATTENDANCE_SUMMARY_REQUEST = 'GET_ATTENDANCE_SUMMARY_REQUEST';
export const GET_ATTENDANCE_SUMMARY_SUCCESS = 'GET_ATTENDANCE_SUMMARY_SUCCESS';
export const GET_ATTENDANCE_SUMMARY_FAILURE = 'GET_ATTENDANCE_SUMMARY_FAILURE';
