export const ADD_CLIENT_REQUEST = 'ADD_CLIENT_REQUEST';
export const ADD_CLIENT_SUCCESS = 'ADD_CLIENT_SUCCESS';
export const ADD_CLIENT_FAILURE = 'ADD_CLIENT_FAILURE';

export const GET_CLIENT_LIST_REQUEST = 'GET_CLIENT_LIST_REQUEST';
export const GET_CLIENT_LIST_SUCCESS = 'GET_CLIENT_LIST_SUCCESS';
export const GET_CLIENT_LIST_FAILURE = 'GET_CLIENT_LIST_FAILURE';

export const UPDATE_CLIENT_STATUS_REQUEST = 'UPDATE_CLIENT_STATUS_REQUEST';
export const UPDATE_CLIENT_STATUS_SUCCESS = 'UPDATE_CLIENT_STATUS_SUCCESS';
export const UPDATE_CLIENT_STATUS_FAILURE = 'UPDATE_CLIENT_STATUS_FAILURE';

export const GET_CLIENT_DETAIL_REQUEST = 'GET_CLIENT_DETAIL_REQUEST';
export const GET_CLIENT_DETAIL_SUCCESS = 'GET_CLIENT_DETAIL_SUCCESS';
export const GET_CLIENT_DETAIL_FAILURE = 'GET_CLIENT_DETAIL_FAILURE';

export const DELETE_CLIENT_REQUEST = 'DELETE_CLIENT_REQUEST';
export const DELETE_CLIENT_SUCCESS = 'DELETE_CLIENT_SUCCESS';
export const DELETE_CLIENT_FAILURE = 'DELETE_CLIENT_FAILURE';

export const GET_CLIENT_PROJECT_DETAIL_REQUEST = 'GET_CLIENT_PROJECT_DETAIL_REQUEST';
export const GET_CLIENT_PROJECT_DETAIL_SUCCESS = 'GET_CLIENT_PROJECT_DETAIL_SUCCESS';
export const GET_CLIENT_PROJECT_DETAIL_FAILURE = 'GET_CLIENT_PROJECT_DETAIL_FAILURE';


