

export const ADD_DEPARTMENT_REQUEST = 'ADD_DEPARTMENT_REQUEST';
export const ADD_DEPARTMENT_SUCCESS = 'ADD_DEPARTMENT_SUCCESS';
export const ADD_DEPARTMENT_FAILURE = 'ADD_DEPARTMENT_FAILURE';

export const GET_DEPARTMENT_LIST_REQUEST = 'GET_DEPARTMENT_LIST_REQUEST';
export const GET_DEPARTMENT_LIST_SUCCESS = 'GET_DEPARTMENT_LIST_SUCCESS';
export const GET_DEPARTMENT_LIST_FAILURE = 'GET_DEPARTMENT_LIST_FAILURE';

export const UPDATE_DEPARTMENT_STATUS_REQUEST = 'UPDATE_DEPARTMENT_STATUS_REQUEST';
export const UPDATE_DEPARTMENT_STATUS_SUCCESS = 'UPDATE_DEPARTMENT_STATUS_SUCCESS';
export const UPDATE_DEPARTMENT_STATUS_FAILURE = 'UPDATE_DEPARTMENT_STATUS_FAILURE';

export const GET_DEPARTMENT_DETAIL_REQUEST = 'GET_DEPARTMENT_DETAIL_REQUEST';
export const GET_DEPARTMENT_DETAIL_SUCCESS = 'GET_DEPARTMENT_DETAIL_SUCCESS';
export const GET_DEPARTMENT_DETAIL_FAILURE = 'GET_DEPARTMENT_DETAIL_FAILURE';

export const DELETE_DEPARTMENT_REQUEST = 'DELETE_DEPARTMENT_REQUEST';
export const DELETE_DEPARTMENT_SUCCESS = 'DELETE_DEPARTMENT_SUCCESS';
export const DELETE_DEPARTMENT_FAILURE = 'DELETE_DEPARTMENT_FAILURE';

export const GET_EMPLOYEE_DEPARTMENT_DETAIL_REQUEST = 'GET_EMPLOYEE_DEPARTMENT_DETAIL_REQUEST';
export const GET_EMPLOYEE_DEPARTMENT_DETAIL_SUCCESS = 'GET_EMPLOYEE_DEPARTMENT_DETAIL_SUCCESS';
export const GET_EMPLOYEE_DEPARTMENT_DETAIL_FAILURE = 'GET_EMPLOYEE_DEPARTMENT_DETAIL_FAILURE';

export const GET_DEPARTMENT_PROJECT_DETAIL_REQUEST = 'GET_DEPARTMENT_PROJECT_DETAIL_REQUEST';
export const GET_DEPARTMENT_PROJECT_DETAIL_SUCCESS = 'GET_DEPARTMENT_PROJECT_DETAIL_SUCCESS';
export const GET_DEPARTMENT_PROJECT_DETAIL_FAILURE = 'GET_DEPARTMENT_PROJECT_DETAIL_FAILURE';