export const ADD_DESIGNATION_REQUEST = 'ADD_DESIGNATION_REQUEST';
export const ADD_DESIGNATION_SUCCESS = 'ADD_DESIGNATION_SUCCESS';
export const ADD_DESIGNATION_FAILURE = 'ADD_DESIGNATION_FAILURE';

export const GET_DESIGNATION_LIST_REQUEST = 'GET_DESIGNATION_LIST_REQUEST';
export const GET_DESIGNATION_LIST_SUCCESS = 'GET_DESIGNATION_LIST_SUCCESS';
export const GET_DESIGNATION_LIST_FAILURE = 'GET_DESIGNATION_LIST_FAILURE';

export const UPDATE_DESIGNATION_STATUS_REQUEST = 'UPDATE_DESIGNATION_STATUS_REQUEST';
export const UPDATE_DESIGNATION_STATUS_SUCCESS = 'UPDATE_DESIGNATION_STATUS_SUCCESS';
export const UPDATE_DESIGNATION_STATUS_FAILURE = 'UPDATE_DESIGNATION_STATUS_FAILURE';

export const GET_DESIGNATION_DETAIL_REQUEST = 'GET_DESIGNATION_DETAIL_REQUEST';
export const GET_DESIGNATION_DETAIL_SUCCESS = 'GET_DESIGNATION_DETAIL_SUCCESS';
export const GET_DESIGNATION_DETAIL_FAILURE = 'GET_DESIGNATION_DETAIL_FAILURE';

export const DELETE_DESIGNATION_REQUEST = 'DELETE_DESIGNATION_REQUEST';
export const DELETE_DESIGNATION_SUCCESS = 'DELETE_DESIGNATION_SUCCESS';
export const DELETE_DESIGNATION_FAILURE = 'DELETE_DESIGNATION_FAILURE';

export const GET_EMPLOYEE_DESIGNATION_DETAIL_REQUEST = 'GET_EMPLOYEE_DESIGNATION_DETAIL_REQUEST';
export const GET_EMPLOYEE_DESIGNATION_DETAIL_SUCCESS = 'GET_EMPLOYEE_DESIGNATION_DETAIL_SUCCESS';
export const GET_EMPLOYEE_DESIGNATION_DETAIL_FAILURE = 'GET_EMPLOYEE_DESIGNATION_DETAIL_FAILURE';