export const ADD_EMP_HEALTH_REQUEST = 'ADD_EMP_HEALTH_REQUEST';
export const ADD_EMP_HEALTH_SUCCESS = 'ADD_EMP_HEALTH_SUCCESS';
export const ADD_EMP_HEALTH_FAILURE = 'ADD_EMP_HEALTH_FAILURE';

export const GET_EMP_HEALTH_LIST_REQUEST = 'GET_EMP_HEALTH_LIST_REQUEST';
export const GET_EMP_HEALTH_LIST_SUCCESS = 'GET_EMP_HEALTH_LIST_SUCCESS';
export const GET_EMP_HEALTH_LIST_FAILURE = 'GET_EMP_HEALTH_LIST_FAILURE';

export const UPDATE_EMP_HEALTH_STATUS_REQUEST = 'UPDATE_EMP_HEALTH_STATUS_REQUEST';
export const UPDATE_EMP_HEALTH_STATUS_SUCCESS = 'UPDATE_EMP_HEALTH_STATUS_SUCCESS';
export const UPDATE_EMP_HEALTH_STATUS_FAILURE = 'UPDATE_EMP_HEALTH_STATUS_FAILURE';

export const GET_EMP_HEALTH_DETAIL_REQUEST = 'GET_EMP_HEALTH_DETAIL_REQUEST';
export const GET_EMP_HEALTH_DETAIL_SUCCESS = 'GET_EMP_HEALTH_DETAIL_SUCCESS';
export const GET_EMP_HEALTH_DETAIL_FAILURE = 'GET_EMP_HEALTH_DETAIL_FAILURE';

export const DELETE_EMP_HEALTH_REQUEST = 'DELETE_EMP_HEALTH_REQUEST';
export const DELETE_EMP_HEALTH_SUCCESS = 'DELETE_EMP_HEALTH_SUCCESS';
export const DELETE_EMP_HEALTH_FAILURE = 'DELETE_EMP_HEALTH_FAILURE';

