export const ADD_FILE_REQUEST = 'ADD_FILE_REQUEST';
export const ADD_FILE_SUCCESS = 'ADD_FILE_SUCCESS';
export const ADD_FILE_FAILURE = 'ADD_FILE_FAILURE';

export const GET_FILE_LIST_REQUEST = 'GET_FILE_LIST_REQUEST';
export const GET_FILE_LIST_SUCCESS = 'GET_FILE_LIST_SUCCESS';
export const GET_FILE_LIST_FAILURE = 'GET_FILE_LIST_FAILURE';

export const GET_FILE_DETAIL_REQUEST = 'GET_FILE_DETAIL_REQUEST';
export const GET_FILE_DETAIL_SUCCESS = 'GET_FILE_DETAIL_SUCCESS';
export const GET_FILE_DETAIL_FAILURE = 'GET_FILE_DETAIL_FAILURE';

export const DELETE_FILE_REQUEST = 'DELETE_FILE_REQUEST';
export const DELETE_FILE_SUCCESS = 'DELETE_FILE_SUCCESS';
export const DELETE_FILE_FAILURE = 'DELETE_FILE_FAILURE';