export const ADD_HOLIDAY_REQUEST = 'ADD_HOLIDAY_REQUEST';
export const ADD_HOLIDAY_SUCCESS = 'ADD_HOLIDAY_SUCCESS';
export const ADD_HOLIDAY_FAILURE = 'ADD_HOLIDAY_FAILURE';

export const GET_HOLIDAY_LIST_REQUEST = 'GET_HOLIDAY_LIST_REQUEST';
export const GET_HOLIDAY_LIST_SUCCESS = 'GET_HOLIDAY_LIST_SUCCESS';
export const GET_HOLIDAY_LIST_FAILURE = 'GET_HOLIDAY_LIST_FAILURE';

export const UPDATE_HOLIDAY_STATUS_REQUEST = 'UPDATE_HOLIDAY_STATUS_REQUEST';
export const UPDATE_HOLIDAY_STATUS_SUCCESS = 'UPDATE_HOLIDAY_STATUS_SUCCESS';
export const UPDATE_HOLIDAY_STATUS_FAILURE = 'UPDATE_HOLIDAY_STATUS_FAILURE';

export const GET_HOLIDAY_DETAIL_REQUEST = 'GET_HOLIDAY_DETAIL_REQUEST';
export const GET_HOLIDAY_DETAIL_SUCCESS = 'GET_HOLIDAY_DETAIL_SUCCESS';
export const GET_HOLIDAY_DETAIL_FAILURE = 'GET_HOLIDAY_DETAIL_FAILURE';

export const DELETE_HOLIDAY_REQUEST = 'DELETE_HOLIDAY_REQUEST';
export const DELETE_HOLIDAY_SUCCESS = 'DELETE_HOLIDAY_SUCCESS';
export const DELETE_HOLIDAY_FAILURE = 'DELETE_HOLIDAY_FAILURE';

