export const ADD_LEAVE_REQUEST = 'ADD_LEAVE_REQUEST';
export const ADD_LEAVE_SUCCESS = 'ADD_LEAVE_SUCCESS';
export const ADD_LEAVE_FAILURE = 'ADD_LEAVE_FAILURE';

export const GET_LEAVE_LIST_REQUEST = 'GET_LEAVE_LIST_REQUEST';
export const GET_LEAVE_LIST_SUCCESS = 'GET_LEAVE_LIST_SUCCESS';
export const GET_LEAVE_LIST_FAILURE = 'GET_LEAVE_LIST_FAILURE';

export const UPDATE_LEAVE_STATUS_REQUEST = 'UPDATE_LEAVE_STATUS_REQUEST';
export const UPDATE_LEAVE_STATUS_SUCCESS = 'UPDATE_LEAVE_STATUS_SUCCESS';
export const UPDATE_LEAVE_STATUS_FAILURE = 'UPDATE_LEAVE_STATUS_FAILURE';

export const GET_LEAVE_DETAIL_REQUEST = 'GET_LEAVE_DETAIL_REQUEST';
export const GET_LEAVE_DETAIL_SUCCESS = 'GET_LEAVE_DETAIL_SUCCESS';
export const GET_LEAVE_DETAIL_FAILURE = 'GET_LEAVE_DETAIL_FAILURE';

export const DELETE_LEAVE_REQUEST = 'DELETE_LEAVE_REQUEST';
export const DELETE_LEAVE_SUCCESS = 'DELETE_LEAVE_SUCCESS';
export const DELETE_LEAVE_FAILURE = 'DELETE_LEAVE_FAILURE';

export const GET_EMPLOYEE_LEAVE_DETAIL_REQUEST = 'GET_EMPLOYEE_LEAVE_DETAIL_REQUEST';
export const GET_EMPLOYEE_LEAVE_DETAIL_SUCCESS = 'GET_EMPLOYEE_LEAVE_DETAIL_SUCCESS';
export const GET_EMPLOYEE_LEAVE_DETAIL_FAILURE = 'GET_EMPLOYEE_LEAVE_DETAIL_FAILURE';

export const GET_LEAVE_SUMMARY_DETAIL_REQUEST = 'GET_LEAVE_SUMMARY_DETAIL_REQUEST';
export const GET_LEAVE_SUMMARY_DETAIL_SUCCESS = 'GET_LEAVE_SUMMARY_DETAIL_SUCCESS';
export const GET_LEAVE_SUMMARY_DETAIL_FAILURE = 'GET_LEAVE_SUMMARY_DETAIL_FAILURE';

export const GET_TODAY_LEAVE_LIST_REQUEST = 'GET_TODAY_LIST_LEAVE_REQUEST';
export const GET_TODAY_LEAVE_LIST_SUCCESS = 'GET_TODAY_LIST_LEAVE_SUCCESS';
export const GET_TODAY_LEAVE_LIST_FAILURE = 'GET_TODAY_LIST_LEAVE_FAILURE';