export const ADD_LEAVE_TYPE_REQUEST = 'ADD_LEAVE_TYPE_REQUEST';
export const ADD_LEAVE_TYPE_SUCCESS = 'ADD_LEAVE_TYPE_SUCCESS';
export const ADD_LEAVE_TYPE_FAILURE = 'ADD_LEAVE_TYPE_FAILURE';

export const GET_LEAVE_TYPE_LIST_REQUEST = 'GET_LEAVE_TYPE_LIST_REQUEST';
export const GET_LEAVE_TYPE_LIST_SUCCESS = 'GET_LEAVE_TYPE_LIST_SUCCESS';
export const GET_LEAVE_TYPE_LIST_FAILURE = 'GET_LEAVE_TYPE_LIST_FAILURE';

export const UPDATE_LEAVE_TYPE_STATUS_REQUEST = 'UPDATE_LEAVE_TYPE_STATUS_REQUEST';
export const UPDATE_LEAVE_TYPE_STATUS_SUCCESS = 'UPDATE_LEAVE_TYPE_STATUS_SUCCESS';
export const UPDATE_LEAVE_TYPE_STATUS_FAILURE = 'UPDATE_LEAVE_TYPE_STATUS_FAILURE';

export const GET_LEAVE_TYPE_DETAIL_REQUEST = 'GET_LEAVE_TYPE_DETAIL_REQUEST';
export const GET_LEAVE_TYPE_DETAIL_SUCCESS = 'GET_LEAVE_TYPE_DETAIL_SUCCESS';
export const GET_LEAVE_TYPE_DETAIL_FAILURE = 'GET_LEAVE_TYPE_DETAIL_FAILURE';

export const DELETE_LEAVE_TYPE_REQUEST = 'DELETE_LEAVE_TYPE_REQUEST';
export const DELETE_LEAVE_TYPE_SUCCESS = 'DELETE_LEAVE_TYPE_SUCCESS';
export const DELETE_LEAVE_TYPE_FAILURE = 'DELETE_LEAVE_TYPE_FAILURE';