export const GET_COUNTRY_LIST_REQUEST = 'GET_COUNTRY_LIST_REQUEST';
export const GET_COUNTRY_LIST_SUCCESS = 'GET_COUNTRY_LIST_SUCCESS';
export const GET_COUNTRY_LIST_FAILURE = 'GET_COUNTRY_LIST_FAILURE';

export const GET_STATE_LIST_REQUEST = 'GET_STATE_LIST_REQUEST';
export const GET_STATE_LIST_SUCCESS = 'GET_STATE_LIST_SUCCESS';
export const GET_STATE_LIST_FAILURE = 'GET_STATE_LIST_FAILURE';

export const GET_CITY_LIST_REQUEST = 'GET_CITY_LIST_REQUEST';
export const GET_CITY_LIST_SUCCESS = 'GET_CITY_LIST_SUCCESS';
export const GET_CITY_LIST_FAILURE = 'GET_CITY_LIST_FAILURE';