export const ADD_PERFORMANCE_REQUEST = 'ADD_PERFORMANCE_REQUEST';
export const ADD_PERFORMANCE_SUCCESS = 'ADD_PERFORMANCE_SUCCESS';
export const ADD_PERFORMANCE_FAILURE = 'ADD_PERFORMANCE_FAILURE';

export const GET_PERFORMANCE_LIST_REQUEST = 'GET_PERFORMANCE_LIST_REQUEST';
export const GET_PERFORMANCE_LIST_SUCCESS = 'GET_PERFORMANCE_LIST_SUCCESS';
export const GET_PERFORMANCE_LIST_FAILURE = 'GET_PERFORMANCE_LIST_FAILURE';

export const UPDATE_PERFORMANCE_STATUS_REQUEST = 'UPDATE_PERFORMANCE_STATUS_REQUEST';
export const UPDATE_PERFORMANCE_STATUS_SUCCESS = 'UPDATE_PERFORMANCE_STATUS_SUCCESS';
export const UPDATE_PERFORMANCE_STATUS_FAILURE = 'UPDATE_PERFORMANCE_STATUS_FAILURE';

export const GET_PERFORMANCE_DETAIL_REQUEST = 'GET_PERFORMANCE_DETAIL_REQUEST';
export const GET_PERFORMANCE_DETAIL_SUCCESS = 'GET_PERFORMANCE_DETAIL_SUCCESS';
export const GET_PERFORMANCE_DETAIL_FAILURE = 'GET_PERFORMANCE_DETAIL_FAILURE';

export const DELETE_PERFORMANCE_REQUEST = 'DELETE_PERFORMANCE_REQUEST';
export const DELETE_PERFORMANCE_SUCCESS = 'DELETE_PERFORMANCE_SUCCESS';
export const DELETE_PERFORMANCE_FAILURE = 'DELETE_PERFORMANCE_FAILURE';

