export const ADD_SHIFT_REQUEST = 'ADD_SHIFT_REQUEST';
export const ADD_SHIFT_SUCCESS = 'ADD_SHIFT_SUCCESS';
export const ADD_SHIFT_FAILURE = 'ADD_SHIFT_FAILURE';

export const ASSIGN_SHIFT_REQUEST = 'ASSIGN_SHIFT_REQUEST';
export const ASSIGN_SHIFT_SUCCESS = 'ASSIGN_SHIFT_SUCCESS';
export const ASSIGN_SHIFT_FAILURE = 'ASSIGN_SHIFT_FAILURE';

export const GET_SHIFT_LIST_REQUEST = 'GET_SHIFT_LIST_REQUEST';
export const GET_SHIFT_LIST_SUCCESS = 'GET_SHIFT_LIST_SUCCESS';
export const GET_SHIFT_LIST_FAILURE = 'GET_SHIFT_LIST_FAILURE';

export const GET_ASSIGN_SHIFT_LIST_REQUEST = 'GET_ASSIGN_SHIFT_LIST_REQUEST';
export const GET_ASSIGN_SHIFT_LIST_SUCCESS = 'GET_ASSIGN_SHIFT_LIST_SUCCESS';
export const GET_ASSIGN_SHIFT_LIST_FAILURE = 'GET_ASSIGN_SHIFT_LIST_FAILURE';

export const UPDATE_SHIFT_STATUS_REQUEST = 'UPDATE_SHIFT_STATUS_REQUEST';
export const UPDATE_SHIFT_STATUS_SUCCESS = 'UPDATE_SHIFT_STATUS_SUCCESS';
export const UPDATE_SHIFT_STATUS_FAILURE = 'UPDATE_SHIFT_STATUS_FAILURE';

export const GET_SHIFT_DETAIL_REQUEST = 'GET_SHIFT_DETAIL_REQUEST';
export const GET_SHIFT_DETAIL_SUCCESS = 'GET_SHIFT_DETAIL_SUCCESS';
export const GET_SHIFT_DETAIL_FAILURE = 'GET_SHIFT_DETAIL_FAILURE';

export const DELETE_SHIFT_REQUEST = 'DELETE_SHIFT_REQUEST';
export const DELETE_SHIFT_SUCCESS = 'DELETE_SHIFT_SUCCESS';
export const DELETE_SHIFT_FAILURE = 'DELETE_SHIFT_FAILURE';

export const GET_ASSIGN_SHIFT_DETAIL_REQUEST = 'GET_ASSIGN_SHIFT_DETAIL_REQUEST';
export const GET_ASSIGN_SHIFT_DETAIL_SUCCESS = 'GET_ASSIGN_SHIFT_DETAIL_SUCCESS';
export const GET_ASSIGN_SHIFT_DETAIL_FAILURE = 'GET_ASSIGN_SHIFT_DETAIL_FAILURE';

export const DELETE_ASSIGN_SHIFT_REQUEST = 'DELETE_ASSIGN_SHIFT_REQUEST';
export const DELETE_ASSIGN_SHIFT_SUCCESS = 'DELETE_ASSIGN_SHIFT_SUCCESS';
export const DELETE_ASSIGN_SHIFT_FAILURE = 'DELETE_ASSIGN_SHIFT_FAILURE';
