export const ADD_TRAINING_REQUEST = 'ADD_TRAINING_REQUEST';
export const ADD_TRAINING_SUCCESS = 'ADD_TRAINING_SUCCESS';
export const ADD_TRAINING_FAILURE = 'ADD_TRAINING_FAILURE';

export const GET_TRAINING_LIST_REQUEST = 'GET_TRAINING_LIST_REQUEST';
export const GET_TRAINING_LIST_SUCCESS = 'GET_TRAINING_LIST_SUCCESS';
export const GET_TRAINING_LIST_FAILURE = 'GET_TRAINING_LIST_FAILURE';

export const UPDATE_TRAINING_STATUS_REQUEST = 'UPDATE_TRAINING_STATUS_REQUEST';
export const UPDATE_TRAINING_STATUS_SUCCESS = 'UPDATE_TRAINING_STATUS_SUCCESS';
export const UPDATE_TRAINING_STATUS_FAILURE = 'UPDATE_TRAINING_STATUS_FAILURE';

export const GET_TRAINING_DETAIL_REQUEST = 'GET_TRAINING_DETAIL_REQUEST';
export const GET_TRAINING_DETAIL_SUCCESS = 'GET_TRAINING_DETAIL_SUCCESS';
export const GET_TRAINING_DETAIL_FAILURE = 'GET_TRAINING_DETAIL_FAILURE';

export const DELETE_TRAINING_REQUEST = 'DELETE_TRAINING_REQUEST';
export const DELETE_TRAINING_SUCCESS = 'DELETE_TRAINING_SUCCESS';
export const DELETE_TRAINING_FAILURE = 'DELETE_TRAINING_FAILURE';

