export const ADD_TRAINERS_REQUEST = 'ADD_TRAINERS_REQUEST';
export const ADD_TRAINERS_SUCCESS = 'ADD_TRAINERS_SUCCESS';
export const ADD_TRAINERS_FAILURE = 'ADD_TRAINERS_FAILURE';

export const GET_TRAINERS_LIST_REQUEST = 'GET_TRAINERS_LIST_REQUEST';
export const GET_TRAINERS_LIST_SUCCESS = 'GET_TRAINERS_LIST_SUCCESS';
export const GET_TRAINERS_LIST_FAILURE = 'GET_TRAINERS_LIST_FAILURE';

export const UPDATE_TRAINERS_STATUS_REQUEST = 'UPDATE_TRAINERS_STATUS_REQUEST';
export const UPDATE_TRAINERS_STATUS_SUCCESS = 'UPDATE_TRAINERS_STATUS_SUCCESS';
export const UPDATE_TRAINERS_STATUS_FAILURE = 'UPDATE_TRAINERS_STATUS_FAILURE';

export const GET_TRAINERS_DETAIL_REQUEST = 'GET_TRAINERS_DETAIL_REQUEST';
export const GET_TRAINERS_DETAIL_SUCCESS = 'GET_TRAINERS_DETAIL_SUCCESS';
export const GET_TRAINERS_DETAIL_FAILURE = 'GET_TRAINERS_DETAIL_FAILURE';

export const DELETE_TRAINERS_REQUEST = 'DELETE_TRAINERS_REQUEST';
export const DELETE_TRAINERS_SUCCESS = 'DELETE_TRAINERS_SUCCESS';
export const DELETE_TRAINERS_FAILURE = 'DELETE_TRAINERS_FAILURE';

export const GET_TRAINERS_HISTORY_REQUEST = 'GET_TRAINERS_HISTORY_REQUEST';
export const GET_TRAINERS_HISTORY_SUCCESS = 'GET_TRAINERS_HISTORY_SUCCESS';
export const GET_TRAINERS_HISTORY_FAILURE = 'GET_TRAINERS_HISTORY_FAILURE';

