export const ADD_TRAVEL_REQUEST = 'ADD_TRAVEL_REQUEST';
export const ADD_TRAVEL_SUCCESS = 'ADD_TRAVEL_SUCCESS';
export const ADD_TRAVEL_FAILURE = 'ADD_TRAVEL_FAILURE';

export const GET_TRAVEL_LIST_REQUEST = 'GET_TRAVEL_LIST_REQUEST';
export const GET_TRAVEL_LIST_SUCCESS = 'GET_TRAVEL_LIST_SUCCESS';
export const GET_TRAVEL_LIST_FAILURE = 'GET_TRAVEL_LIST_FAILURE';

export const GET_TRAVEL_DETAIL_REQUEST = 'GET_TRAVEL_DETAIL_REQUEST';
export const GET_TRAVEL_DETAIL_SUCCESS = 'GET_TRAVEL_DETAIL_SUCCESS';
export const GET_TRAVEL_DETAIL_FAILURE = 'GET_TRAVEL_DETAIL_FAILURE';

export const DELETE_TRAVEL_REQUEST = 'DELETE_TRAVEL_REQUEST';
export const DELETE_TRAVEL_SUCCESS = 'DELETE_TRAVEL_SUCCESS';
export const DELETE_TRAVEL_FAILURE = 'DELETE_TRAVEL_FAILURE';

export const GET_TRAVEL_HISTORY_DETAIL_REQUEST = 'GET_TRAVEL_HISTORY_DETAIL_REQUEST';
export const GET_TRAVEL_HISTORY_DETAIL_SUCCESS = 'GET_TRAVEL_HISTORY_DETAIL_SUCCESS';
export const GET_TRAVEL_HISTORY_DETAIL_FAILURE = 'GET_TRAVEL_HISTORY_DETAIL_FAILURE';